github: [metadata]
title: Аэростат
url: http://aerostat.rocks
description: цикл передач для Радио России
keywords: Аэростат, Аквариум, БГ, Гребенщиков, Борис Гребенщиков
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-paginate
    - jekyll-feed
paginate: 20
