github: [metadata]
title: "Аэростат: Авторская программа Бориса Гребенщикова"
url: http://aerostat.rocks
description: цикл передач для Радио России
keywords: Аэростат, Аквариум, БГ, Гребенщиков, Борис Гребенщиков, все выпуски
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
paginate: 20
